//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST465Project_StephanieVetter.Web_Forms {
    
    
    public partial class ValidateForm {
        
        /// <summary>
        /// reqTextBoxPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel reqTextBoxPanel;
        
        /// <summary>
        /// uxName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465Project_StephanieVetter.Web_Forms.ValidatedTextBox uxName;
        
        /// <summary>
        /// uxFavColor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465Project_StephanieVetter.Web_Forms.ValidatedTextBox uxFavColor;
        
        /// <summary>
        /// uxCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465Project_StephanieVetter.Web_Forms.ValidatedTextBox uxCity;
        
        /// <summary>
        /// uxSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button uxSubmit;
    }
}
